# # Elastic deformation
#
# Authors: Jack. S. Hale and Jørgen S. Dokken
#
# In this example, we will show how to use FEniCS to solve the equations of linear elasticity and hyper-elasticity with FEniCS.
# We start by importing the required modules.

# +
from mpi4py import MPI

import dolfinx.fem.petsc
import basix.ufl
# -

# # Loading meshes
# DOLFINx has a wide range of ways of loading meshes. One of the most common formats is the `.msh` format, which we provide wrappers for

mesh_data = dolfinx.io.gmsh.read_from_msh("mesh.msh", comm=MPI.COMM_WORLD, rank=0)
domain = mesh_data.mesh
cell_tags = mesh_data.cell_tags
facet_tags = mesh_data.facet_tags

# We can for instance inspect the geometry with pyvista

import pyvista

grid = pyvista.UnstructuredGrid(*dolfinx.plot.vtk_mesh(domain))
plotter = pyvista.Plotter()
plotter.add_mesh(grid, show_edges=True)
plotter.show()

# The grid is actually second order, to see this with pyvista we use

plotter = pyvista.Plotter()
curved_grid = grid.tessellate()
plotter.add_mesh(curved_grid)
plotter.show()

# We can store the mesh to XDMF to visualize it in Paraview

with dolfinx.io.XDMFFile(domain.comm, "mesh.xdmf", "w") as xdmf:
    xdmf.write_mesh(domain)
    xdmf.write_meshtags(facet_tags, domain.geometry)

# ![Example tool from CAD generated by Joe Dean (University of Cambridge)](./example_tool.png)

breakpoint()

